### ISSUE TITLE
Interleaved 2 of 5 doesn’t seem to reflect data

### ISSUE THREAD

**Issue by binki** [barnhill/barcodelib#111]
![image](https://user-images.githubusercontent.com/82626/100634374-3ad3b600-32fd-11eb-997f-64ca051635d5.png)

The pattern in the middle doesn’t change when I change the input “Value to Encode”. Same with Interleaved 2 of 5 mod 2.

**Comment by barnhill** [comment]
ugh oh ... yep we should look into this asap.  Just released the fix for S2of5 last night
