### ISSUE TITLE
Standard 2 of 5 encoding is incorrect

### ISSUE THREAD

**Issue by barnhill** [barnhill/barcodelib#113]
![Capture](https://user-images.githubusercontent.com/3878158/101267305-d2317280-371c-11eb-8306-5a369f518e79.JPG)

**Comment by pablopioli** [comment]
See it resolved in 2.2.9. Thanks!

**Comment by oSethoum** [comment]
How did you put the image there ? Am looking for a way to load the image generated to the Image xaml tag.

**Comment by barnhill** [comment]
> How did you put the image there ? Am looking for a way to load the image generated to the Image xaml tag.

I put the generated image into an Image control.  Pretty simple.
