### ISSUE TITLE
.net 4.0 Support?

### ISSUE THREAD

**Issue by abhijeetk1810** [barnhill/barcodelib#114]
Hello All,

I am trying to install via NuGet and getting the following error:

Installing 'BarcodeLib 2.2.9'.
Successfully installed 'BarcodeLib 2.2.9'.
Adding 'BarcodeLib 2.2.9' to Library Management System.
Uninstalling 'BarcodeLib 2.2.9'.
Successfully uninstalled 'BarcodeLib 2.2.9'.
Install failed. Rolling back...
Could not install package 'BarcodeLib 2.2.9'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.0,Profile=Client', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

My Target framework is .net 4.0

**Comment by barnhill** [comment]
Maybe it's the transitive dependency?



Brad Barnhill, MSN, RN
bradbarnhill@hotmail.com

**Comment by barnhill** [comment]
Not sure that the dependency `System.Drawing.Common` supports 4.0.0

https://www.nuget.org/packages/System.Drawing.Common/

**Comment by danielchalmers** [comment]
barcodelib targets [.NET Standard 2.0](https://devblogs.microsoft.com/dotnet/announcing-net-standard-2-0) which requires at least 4.6.1

**Comment by barnhill** [comment]
Closing per @danielchalmers comment
