### ISSUE TITLE
How to display Barcode below the image?

### ISSUE THREAD

**Issue by SreeKrishnatsr** [barnhill/barcodelib#115]
I would like to display barcode bottom of the image, So when user unable to scan they can read the value

**Comment by binki** [comment]
Hi @SreeKrishnatsr 

The text inside the barcode image is called a “label”. You can enable the label by setting the `IncludeLabel` property to `true`. For example, if you have code like this:

```csharp
var b = new BarcodeLib.Barcode();
using (var img = b.Encode(BarcodeLib.TYPE.UPCA, "038000356216", Color.Black, Color.White, 290, 120)) {
}
```

you can alter that to the following to show the label:

```csharp
var b = new BarcodeLib.Barcode {
    IncludeLabel = true,
};
using (var img = b.Encode(BarcodeLib.TYPE.UPCA, "038000356216", Color.Black, Color.White, 290, 120)) {
}
```
