### ISSUE TITLE
Different behavior of DataTable with unicode in NET 5

### ISSUE THREAD

**Issue by jangernert** [barnhill/barcodelib#123]
First things first: everything seems fine in .NET Framework (4.7/4.8) and .NET Core 3.1

Switching to NET 5 causes unicode characters (`\u0014` & `\u0012` in my case) to always get encoded as generic space. I tracked the issue down to the select method of the `DataTable C128_Code;`. In net core querying a unicode character returns only the desired `DataRow`.

NET 5 however behaves differently, as it spits out  28 different rows always starting with `"0", " ", " ", "00", "11011001100"`. The correct row is always part of the query result. So it can be found with a loop and some string-comparison. But that seems very backwards. I'm not sure why the `DataTable.Select()` behavior would change in NET 5. But that seems to be a big problem for this otherwise great library.

**Comment by jangernert** [comment]
I found some information on the breaking NET 5 change: https://docs.microsoft.com/en-us/dotnet/standard/base-types/string-comparison-net-5-plus

But no easy fix. The bug seems to exist with .NET Core as well, but only on non-windows platforms. My guess is that something goes wrong dissecting the query string inside of [`DataTable`](https://github.com/dotnet/runtime/blob/master/src/libraries/System.Data.Common/src/System/Data/DataTable.cs#L4207). A workaround would be to use LINQ instead. Although I haven't compared the performance of the two solutions

```
// original code
E_Row = C128_Code.Select("A = '" + s1 + "'");

// LINQ
E_Row = C128_Code.AsEnumerable().Where(row => row["A"].ToString() == s1).ToArray();
```

The LINQ works for me. Not sure what to make of all of this.

**Comment by binki** [comment]
I haven’t looked directly, but I would guess that getting rid of `DataTable` and instead using different structures like `Dictionary<TKey, TValue>` or `ToLookup` could make things more type-safe and clearer and probably faster too. If it also fixes a portability issue, that is probably the right way to go.

**Comment by jangernert** [comment]
That's also a way to solve this. I wanted to introduce minimal changes as this was the first time I took a look at the code.

**Comment by barnhill** [comment]
Do either of you want to create a PR?

Brad Barnhill, MSN, RN
bradbarnhill@hotmail.com

**Comment by jangernert** [comment]
I can give it a try early next week.
