### ISSUE TITLE
Please Add Send Image To Printer 

### ISSUE THREAD

**Issue by aliChavoshi** [barnhill/barcodelib#129]
Please Add Send Image To Printer  Thanks

**Comment by barnhill** [comment]
I don't think that belongs in this library. This generates the image and then using .net you can send it to a printer already.  Everyone will want it formatted differently when printed, or printed on different paper sizes etc

**Comment by aliChavoshi** [comment]
I User Print Document Library in c# 
Thanks

**Comment by binki** [comment]
@aliChavoshi 
> I Use Print Document Library in c#
> Thanks

I don’t know this library. Could you provide a link to help me understand you?

Thanks.

**Comment by aliChavoshi** [comment]
Please come to my GitHub and check out the barcode project

**Comment by barnhill** [comment]
Closing this as answered.
