### ISSUE TITLE
QR Code

### ISSUE THREAD

**Issue by roland78** [barnhill/barcodelib#137]
Hello, 

Any plans on supporting QR Code? (https://en.wikipedia.org/wiki/QR_code)

**Comment by barnhill** [comment]
I'd love to!  Just need to get the community to help implement it

Brad Barnhill, MSN, RN
***@***.***

**Comment by rob313663** [comment]
QR is like 10 times harder than implementing all the 1D barcodes there is.
Reed Solomon algo and stuff, above my math knowledge. There are open source
implementations for QR. Search for Zxing.

/rob

**Comment by barnhill** [comment]
Closing as it would be wonderful to include 2d barcodes but I need community support for that.
