### ISSUE TITLE
Issue with underscore in input.

### ISSUE THREAD

**Issue by chvvrajesh** [barnhill/barcodelib#138]
Hello,

Unhandelled exception while trying to generate barcode(39) for input that contains underscore(_).

Any workaround for this issue?

![image](https://user-images.githubusercontent.com/3823688/145968371-a6ee89e2-0974-4584-ac70-be3c3e7e5888.png)

Thanks

**Comment by rob313663** [comment]
Underscore is not a valid character in Code 39. Could have been a more
specific exception maybe.

If you can, use Code 128 instead.

https://en.m.wikipedia.org/wiki/Code_39

/rob

**Comment by barnhill** [comment]
just tested this with Code39 and it gives you a better message:

![image](https://user-images.githubusercontent.com/3878158/229399026-e558ec05-2b5b-4ba4-9c24-be9bfabdc271.png)
