### ISSUE TITLE
A generic error occurred in GDI+. in WPF.Net c#

### ISSUE THREAD

**Issue by nasusonetrick** [barnhill/barcodelib#145]
```
            Barcode b = new Barcode();
            System.Drawing.Image img = b.Encode(BarcodeLib.TYPE.EAN13, "038000356216", Color.Black, Color.White, 400, 200);

            // Store image in some path with the desired format
            img.Save(@"C:UserssdkcaDesktopean13_example.png", ImageFormat.Png);
```

is giving me the error : ( **A generic error occurred in GDI+** ) ???

**Comment by barnhill** [comment]
What version of the .net sdk are you using?

**Comment by nasusonetrick** [comment]
> 

im using **4.7 net framework**

the issue was that i didn't use MemoryStream with **using() clause** properly 
my apologies for wasting your time .

by the way when the code bar Format is not correct it throw an error , anyway to generate the codebar even if the chars count are less than 13 in ( EAN ) TYPE ? 
or should i check for char.Length < 13 , then i change the type ?! which one that accept small and large range of numbers !

**Comment by barnhill** [comment]
Those exceptions are because they are invalid inputs according to the specs.

**Comment by barnhill** [comment]
The example app has example code in it.  Also no worries on wasting my time. I'm here to try to help 🙂👍

**Comment by barnhill** [comment]
For large numbers of variable length C128 might be the best option.
