### ISSUE TITLE
Include code line to the Wiki for setting boolean value of IncludeLabel property

### ISSUE THREAD

**Issue by dimaminich** [barnhill/barcodelib#148]
Hi Brad,

could you please add the following code line to your example before executing the Encode Method:

`b.IncludeLabel = true;`

so that it is clear if the value set to true the barcode generator adds the numbers below barcode.

Thanks in advance.

**Comment by barnhill** [comment]
I have added this to an upcoming branch that is introducing cross-platform compatibility as well

**Comment by barnhill** [comment]
Here is the pull request: https://github.com/barnhill/barcodelib/pull/152
