### ISSUE TITLE
BarcodeStandard does not have a strong name in NET Standard 2.0

### ISSUE THREAD

**Issue by edisonjromor** [barnhill/barcodelib#153]
`Warning	CS8002	Referenced assembly 'BarcodeStandard, Version=2.4.0.0, Culture=neutral, PublicKeyToken=null' does not have a strong name.`

**Comment by barnhill** [comment]
Where is this message coming from?  Is this when importing it somewhere?

**Comment by barnhill** [comment]
There is a new branch that is updating to SkiaSharp for cross platform support.  I have added signing the assembly in there.
https://github.com/barnhill/barcodelib/pull/152

**Comment by barnhill** [comment]
Closing this as this will be resolved with the PR mentioned above.
