### ISSUE TITLE
Having Issue with SaveImage

### ISSUE THREAD

**Issue by AmyMcD75** [barnhill/barcodelib#159]
Using Version 3.0.0, and using the SaveImage method with a Bmp SaveType. 

Barcodelib is coming back with this error message:

ESAVEIMAGE-1: Could not save image.

=======================
Object reference not set to an instance of an object.

Bmp is a valid Save type, so why am I getting this error message?

**Comment by barnhill** [comment]
Im using the following in the example app just fine on Windows:
```
b.SaveImage("filename.jpg", SaveTypes.Jpg);
```

**Comment by barnhill** [comment]
Apparently there are several formats not supported via the windows codec that SkiaSharp imports which is weird that windows only supports the other 3 in the lib.  I am going to remove BMP support for now till its supported across all platforms.  BMPs are very large in comparison to the other formats so those are more preferred any way.

**Comment by barnhill** [comment]
Here is the commit: https://github.com/barnhill/barcodelib/commit/ff3cb68c43ed69dac8fccd311e7942d1f9df5f4c
