### ISSUE TITLE
Code 39, memory leak

### ISSUE THREAD

**Issue by rob313663** [barnhill/barcodelib#161]
Generating a Code 39 many times leads to a memory leak:

<img width="221" alt="image" src="https://github.com/barnhill/barcodelib/assets/23123057/604767fc-e696-42bb-b3fe-6f8ae77cc6a8">

Code:

private void button1_Click(object sender, EventArgs e)
{
	SKImage img = null;

	var warmup = new BarcodeStandard.Barcode();
	img = warmup.Encode(BarcodeStandard.Type.Code39, "0", 777, 250);

	Stopwatch sw = Stopwatch.StartNew();

	for (int i = 0; i < 1000; i++)
	{
		var x = new BarcodeStandard.Barcode();
		x.IncludeLabel = true;
		img = x.Encode(BarcodeStandard.Type.Code39Extended, "A1234567890a", 777, 250);
	}
	sw.Stop();
	Debug.WriteLine($"{sw.ElapsedMilliseconds} ms");

	img.Dispose();
}

**Comment by rob313663** [comment]
My implementation:

<img width="226" alt="image" src="https://github.com/barnhill/barcodelib/assets/23123057/7fdf65ff-4e42-43de-a199-933dc9154dc6">

**Comment by rob313663** [comment]
Ran it for a longer time, I was probably wrong. It seems stable.

**Comment by barnhill** [comment]
I think this is just due to the delay before garbage collection ... if the system gets under memory pressure or the GC is scheduled to run it will drop in memory usage.  I see this a lot.
