### ISSUE TITLE
Suggestion for improvement

### ISSUE THREAD

**Issue by rob313663** [barnhill/barcodelib#166]
Hi!

A good thing to improve BarcodeLib would be to make tests for all barcode types using all the valid data characters when generating a barcode and then use ZXing to read the generated barcodes.

Adding a property on every barcode type called ValidDataCharacters (works for Code 39, Interleaved 2 of 5 and Codabar so far, Code 128 will be probably be a bit harder) and using RandomizeString() and running it a couple of hundred times and checking against what ZXing says would a very good test:

<img width="491" alt="image" src="https://github.com/barnhill/barcodelib/assets/23123057/a71fabff-e154-4cff-8459-3dcccb4a6746">

<img width="569" alt="image" src="https://github.com/barnhill/barcodelib/assets/23123057/8dbb9085-81ac-4aa0-b99f-8fc99247f7b5">

/rob

**Comment by barnhill** [comment]
Then the library is only as strong as ZXing and if they have a bug we follow them down that rabbit hole.  I would rather test against known good encoding thats have been tested via several barcode readers which is what the unit tests currently do by testing the encoded values.

**Comment by barnhill** [comment]
I did utilize the faster numeric check with very marginal differences but it may be faster with my crud testing. 
https://github.com/barnhill/barcodelib/commit/4b0de50f18b845864b43d1702e7121920f421a20
