### ISSUE TITLE
FIM has an E

### ISSUE THREAD

**Issue by rob313663** [barnhill/barcodelib#172]
Since 2010, FIM has a code for E.

https://about.usps.com/publications/pub25/pub25_ch10_003.htm

FIM E: | |   | | (101000101)

/rob

**Comment by barnhill** [comment]
Some how the Java version of this lib has FIM_E in it but the C# didnt get that update :)  This is fixed here:

https://github.com/barnhill/barcodelib/commit/356aae8f94a6ba984e27e198dcc4762ab7dfa94a
