### ISSUE TITLE
POSTNET, height of "half" bars

### ISSUE THREAD

**Issue by rob313663** [barnhill/barcodelib#173]
y = ilHeight / 2f;

should be

y = ilHeight * 0.4f;

It is incorrect on the wikipedia page too.

https://web.archive.org/web/20050118015758/http://www.siemons.com/forms/pdf/designing_letter_reply_mail.pdf

Page 34:

0.050" / 0.125" = 0.4

<img width="576" alt="image" src="https://github.com/barnhill/barcodelib/assets/23123057/98e7abfd-17ae-45cf-b4a7-f72e11aae3e4">

**Comment by barnhill** [comment]
I think you are right it should be:

```
y = ilHeight - ilHeight * 0.4f;
```

**Comment by barnhill** [comment]
Fixed with: https://github.com/barnhill/barcodelib/commit/8695a4eedc5488bbc4251b61764574b1a5de3be2
