### ISSUE TITLE
.NET Framework 4.8

### ISSUE THREAD

**Issue by talley** [barnhill/barcodelib#176]
It does not work with .NET Framework 4.8

**Comment by barnhill** [comment]
The example application in this repo uses .NET Framework 4.8 ... is there something else you are seeing?

**Comment by duploman** [comment]
Barcode exists only in BarcodeStandard, but Encode method has not the same signature.

**Comment by barnhill** [comment]
Looks like there is a need to do some namespace cleanup and get them all in BarcodeStandard.  Ill fix this.

**Comment by barnhill** [comment]
This should be cleaned up with this PR: https://github.com/barnhill/barcodelib/pull/203
