### ISSUE TITLE
Barcode type: IATA 2 of 5

### ISSUE THREAD

**Issue by rob313663** [barnhill/barcodelib#177]
Suggestion, add the IATA 2 o 5 barcode. It should be really simple since the only difference is the start and stop patterns.

This is my implementation so far:

`using Robbar.Renderers;

namespace Robbar
{
    public class IATA2of5 : Standard2of5
    {
        public static new string SymbologyName { get; } = "IATA 2 of 5";
        public static new string[] SymbologyAliasNames { get; } = { "Computer Identics 2 of 5", "Airline 2 of 5" };

        public IATA2of5()
        {
            StartCodeWord = new CodeWord() { Pattern = "bsb", Text = "" };
            StopCodeWord = new CodeWord() { Pattern = "Bsb", Text = "" };
        }
    }
}`

**Comment by barnhill** [comment]
Adding IATA2of5 here: https://github.com/barnhill/barcodelib/pull/201

Going to push this out shortly if you want to give it a review.

**Comment by barnhill** [comment]
Added IATA 2 of 5 support in 3.1.0 https://github.com/barnhill/barcodelib/releases/tag/3.1.0
