### ISSUE TITLE
Add Strong Name for usage in COM DLLs

### ISSUE THREAD

**Issue by WebsiteDeveloper** [barnhill/barcodelib#19]
I would like to use this library in a com library i use but i need a strong name in the dll to invoke the function call.
Could you maybe add this or i could add a pull.

**Comment by WebsiteDeveloper** [comment]
@barnhill

**Comment by barnhill** [comment]
if you would like to add a pull request for this id be glad to accept pulls

**Comment by WebsiteDeveloper** [comment]
Fixed by 972ccd4bd856b9b5289ca640242d00ae7c80c8c8
