### ISSUE TITLE
Compilation error (Latest version visual Studio)

### ISSUE THREAD

**Issue by robertjb20** [barnhill/barcodelib#191]
I received the following error message:

Severity	Code	Description	Project	File	Line	Suppression State
Error		Couldn't process file TestApp.resx due to its being in the Internet or Restricted zone or having the mark of the web on the file. Remove the mark of the web if you want to process these files.	BarcodeStandardExample.

Thank you.

**Comment by barnhill** [comment]
Does this help https://stackoverflow.com/a/51349305

**Comment by barnhill** [comment]
Did you pull this down via git or a zip file

**Comment by robertjb20** [comment]
Yes, it does solve the problem. Thank you.
