### ISSUE TITLE
After updating 2.4.0 to 3.0.3 I faced this issue while the backColor is transparent for the barcode

### ISSUE THREAD

**Issue by Kirubakarane-Raman** [barnhill/barcodelib#200]
When the bar code background color is transparent. The label is not showing below the barcode. Instead of it the text and the barcode gets overlapped.
![image](https://github.com/barnhill/barcodelib/assets/107405032/2f95cc90-63d4-4434-ace2-f305556b7c92)

Is there any solution to resolve this?

**Comment by barnhill** [comment]
Should be addressed here: https://github.com/barnhill/barcodelib/commit/ad968801013e41884b3bc6871b9c744d524f25a4 

Also just published 3.0.4 to take care of this.  Closing this issue and if it reappears please reopen an issue.

**Comment by Kirubakarane-Raman** [comment]
I am still getting this issue after the version update.
