### ISSUE TITLE
After updating 2.4.0 to 3.0.4 I faced this issue while the backColor is transparent for the barcode

### ISSUE THREAD

**Issue by Kirubakarane-Raman** [barnhill/barcodelib#204]
I had raised this query earlier. I am still getting this issue with latest version 3.0.4 also.
https://github.com/barnhill/barcodelib/issues/200

When the bar code background color is transparent. The label is not showing below the barcode. Instead of it the text and the barcode gets overlapped.
![image](https://github.com/barnhill/barcodelib/assets/107405032/2f95cc90-63d4-4434-ace2-f305556b7c92)

Is there any solution to resolve this?

**Comment by Kirubakarane-Raman** [comment]
This above issue got resolved in the latest version 3.1.0. But I am facing an another issue, The number is not properly displayed for EAN-13 bar code. Font size is too big.
![image](https://github.com/barnhill/barcodelib/assets/107405032/963b789d-8884-44c1-8f4b-76e7a74b0cb4)

**Comment by barnhill** [comment]
labels need a lot of work ... they need to resize and they dont today based on the width of the barcode to fit in the space provided.  If the label font is made smaller itll work but that takes manually setting it.

**Comment by barnhill** [comment]
Im going to close this specific issue as resolved with https://github.com/barnhill/barcodelib/releases/tag/3.1.0
