### ISSUE TITLE
During build: libSkiaSharp.dylib could not be found

### ISSUE THREAD

**Issue by vrapp** [barnhill/barcodelib#210]
Whenever I build the project using BarcodeStandard in Visual Studio in Windows (same in 2017 and 2022), there's warning:

The referenced component 'c:\users\myusername\projects\thisproject\packages\SkiaSharp.NativeAssets.macOS.2.88.8\build\net462\..\..\runtimes\osx\native\libSkiaSharp.dylib' could not be found.	

In fact this file does seem to exist and is found during the build, according to Process Monitor:
![1](https://github.com/user-attachments/assets/d9d47165-ccf1-4f7a-9f1c-fed2f0a7f859)

If it's related to MacOS, maybe it would be possible to somehow conditionally exclude it from the NuGet package.

**Comment by barnhill** [comment]
Not sure but Im compiling it on a windows machine and dont seem to have any issues.  Would you be willing to take a look at this issue for mac builds?

**Comment by barnhill** [comment]
looks like its an invalid reference which I just removed and it builds just fine with no more warning

**Comment by barnhill** [comment]
addressed this issue here: https://github.com/barnhill/barcodelib/pull/211

**Comment by barnhill** [comment]
This should now be fixed in 3.1.4 that has just been uploaded to NuGet and will be available as soon as they run their checks on it.

**Comment by vrapp** [comment]
Thanks! It's fixed.

**Comment by vrapp** [comment]
...spoke too soon. It's back. I removed NuGet package from the solution as well as all skiasharp packages . Deleted everything in bin and obj folders.  Searched for all files with "libSkiaSharp.dylib" inside in the project folder and ensured there's nothing. Re-added NuGet package of Barcodelib 3.1.4. This brought back Skiasharp, SkiaSharp.NativeAssests.Linux.Dedependencies, SkiaSharp.NativeAssessts.macOS, and the error reappeared.

The referenced component 'C:\(...)\packages\SkiaSharp.NativeAssets.macOS.2.88.8\build\net462\..\..\runtimes\osx\native\libSkiaSharp.dylib' could not be found.

**Comment by barnhill** [comment]
Are you building this in visual studio or jetbrains rider?
