### ISSUE TITLE
Top LabelPositions Cutoff Barcode

### ISSUE THREAD

**Issue by steve-sheppard** [barnhill/barcodelib#24]
If any of the top LabelPostions are used, the label is drawn over the barcode and empty white space is left at the bottom of the encoded image.

![bottom](https://cloud.githubusercontent.com/assets/11685757/24011707/e1aa75b4-0a51-11e7-9f8a-0db9b6227c80.gif)

![top](https://cloud.githubusercontent.com/assets/11685757/24011711/e42790d8-0a51-11e7-9d5a-e72178969209.gif)

**Comment by steve-sheppard** [comment]
I made the fix and created a pull request.  I'm pretty new to github, so let me know if I did anything improperly.

**Comment by barnhill** [comment]
@steve-sheppard nope looks good to me.  Welcome to github and thanks for the contribution!! 👍
