### ISSUE TITLE
I have a BarcodeLib question!! Please help me~

### ISSUE THREAD

**Issue by ChunYenChen** [barnhill/barcodelib#28]
Dear Brad Barnhill:
     Hello! I am Chun-Yen.I used your BarcodeLib open source since two years ago.Would you like me to solve my problem, please?.How can I set up the barcode's DPI?
Thank you very much!!!

**Comment by piolo94** [comment]
Hi! I'm having the same problem! On screen, everything is fine, but when i print it, it isn't much defined!

**Comment by barnhill** [comment]
Im having a hard time deciphering what is wrong ... the library generates an image and you print it.  Is it not able to be read by a barcode reader?  Do you have any examples because any that I print on a laser printer have all scanned just fine.

**Comment by ChunYenChen** [comment]
Hello Brad Barnhill:
It's not a wrong problem! Always many barcode readers can read the bar code is correct. But I ever had a reader always can't read the bar code. So if the library can set the DPI, I will generate the image to test my barcode reader. thanks!!

**Comment by WebsiteDeveloper** [comment]
@ChunYenChen you can just use the Height and Width Properties to set the image size.

**Comment by barnhill** [comment]
going to close this as answered by @WebsiteDeveloper
