### ISSUE TITLE
using library in SSRS reports

### ISSUE THREAD

**Issue by AndrewZenith** [barnhill/barcodelib#31]
Library is now strong named (which is great), but for use in SSRS reports it needs to now be marked with AllowPartiallyTrustedCallers attribute as discussed here:

https://docs.microsoft.com/en-us/sql/reporting-services/custom-assemblies/using-strong-named-custom-assemblies

Without this using the library in an RDL generates the error: "That assembly does not allow partially trusted callers"

**Comment by WebsiteDeveloper** [comment]
@AndrewZenith  i think i will put in a pull request sometime this weekend
@barnhill Any remarks on this?

**Comment by barnhill** [comment]
Sounds good ... Create a PR and I'll review it :)

**Comment by AndrewZenith** [comment]
I think I've finally worked out how to use GitHub from VS2017.  I have created a pull request.

**Comment by barnhill** [comment]
Addressed by https://github.com/barnhill/barcodelib/pull/34
