### ISSUE TITLE
Could be a .NET Standard / .NET Core library ?

### ISSUE THREAD

**Issue by ignatandrei** [barnhill/barcodelib#32]
Could be a .NET Standard / .NET Core library ?

**Comment by barnhill** [comment]
Can you be more specific?

**Comment by A7medRamadan** [comment]
@ignatandrei  i think it's not possible, because the Library using System.Drawing which is not supported in .NET Standard

**Comment by Misiu** [comment]
@A7medRamadan what about .NET Standard 2.0?
@barnhill  there are alternatives to System.Drawing: https://blogs.msdn.microsoft.com/dotnet/2017/01/19/net-core-image-processing/

**Comment by barnhill** [comment]
Any idea how to use the .net core 2.0 libs to replace the drawing namespaces Im currently using?  Id gladly welcome a pull request!!!

**Comment by barnhill** [comment]
If anyone has the time to create a pull request I'd be glad to take a look

**Comment by zHaytam** [comment]
Hello, I added a .NET Standard 2 version in a Fork. It's available here: https://github.com/zHaytam/barcodelib

**Comment by barnhill** [comment]
@zhaytam I'd be glad to take a look at a pull request. I'm interested to see what the diff looks like.

**Comment by zHaytam** [comment]
@barnhill Honestly there is no added code or nothing, just used System.Drawing.Common instead of the System.Drawing in .NET Framework.

**Comment by barnhill** [comment]
This is going to require bumping the min framework supported to 4.5+ .... any one know of any problems doing that or have any reservations?

**Comment by zHaytam** [comment]
Normally it shouldn't be a problem (choose .NET Standard instead of Core) but if you want you could package it as a different library to avoid problems.

**Comment by barnhill** [comment]
@ignatandrei @zHaytam @Misiu would you guys take a look at https://github.com/barnhill/barcodelib/pull/49

There is a branch here named [net-core-conversion] that you can pull down to take a look if you like.  Thanks for the motivation to get this done and PLEASE let me know if you guys see something that should change.

**Comment by barnhill** [comment]
Pull request for this https://github.com/barnhill/barcodelib/pull/49

**Comment by barnhill** [comment]
@ignatandrei @zHaytam @Misiu unless any objections are noted Im going to merge the pull request I have made to update to support .NET Core 2.0 and .NET Standard 4.6.2

**Comment by barnhill** [comment]
.NET Standard 2.0 branch has been merged and artifact uploaded to nuget.org
