### ISSUE TITLE
A (probably) simple question

### ISSUE THREAD

**Issue by UHDanGal** [barnhill/barcodelib#33]
Hi

I've found this page on my travels through trying to get this to work.

Full disclosure, I'm not a developer!

I've managed to get a string to render in SSRS, but when the length goes over 30 characters, I get a little red X instead.

So, my question(s) are:

1. Is is possible to render strings longer than 30 characters? If so, what might I be doing incorrectly?
2. If not, is it possible to concatenate 2 barcodes after the encode step?

Any help would be greatly appreciated.

I work for Public Sector hospital, so being able to use this barcode to process patients a little faster would be fantastic.

Thanks 

Dan

**Comment by barnhill** [comment]
What are you trying to encode longer than 30 chars?  Appending two barcodes together usually isn't possible.  That would not permit it to scan since most symbologies have guard bars on the ends

**Comment by UHDanGal** [comment]
I'm finding that!

It's a few details of a patients attendance, it is currently handled by existing software, but we're unable to replicate it with anything more than 30 characters.

Identifiers for a clinic, a patient, a clinician and specialty information.

I think I'm nearly there, is there a way, do you know, to stop the left/or guard bar?

thanks for your reply

**Comment by barnhill** [comment]
Trimming off the guard bars and slamming them together isn't going to
work.  You can encode more than 30 chars in c128 barcodes so I'd use those.
