### ISSUE TITLE
When selecting Type EAN13 label only have 12 digits

### ISSUE THREAD

**Issue by andrenpt** [barnhill/barcodelib#38]
Hello,

When I generate a barcode of type EAN13 why is the label only displaying 12 digits ?

Thanks

**Comment by andrenpt** [comment]
Hello again, 

In order to replicate this issue you need to use this sizes (120,55):
`var image = b.Encode(BarcodeLib.TYPE.EAN13, barcodeNumber, Color.Black, Color.White, 120, 55);`


Thanks

**Comment by barnhill** [comment]
The default is to put the exact data you encoded into the label ... now if you wanted to put the encoded value you are able to do that or you can put whatever you want in the label.  The check digit by default isnt put in the label.  The label functionality is pretty generic and applies to all symbologies but Id be open to pull requests that include specific labeling for symbology types.

**Comment by barnhill** [comment]
@andrenpt there is new functionality as of tonight to print EAN-13 labels in a more standard format.  Im going to close this since that is in now.

**Comment by barnhill** [comment]
![ean-label](https://user-images.githubusercontent.com/3878158/38462095-0af3236e-3aa6-11e8-9f0a-4647b1e9c64b.JPG)

**Comment by AmineMessabhia** [comment]
Hey @barnhill, 
First of all, you're awesome!! I found your library and I was soooo relieved i did.
I have version 2.2.2 of the library, but this is how my Barcode EAN-13 shows:

![image](https://user-images.githubusercontent.com/28136152/68032205-814f7f00-fcbd-11e9-9786-0a2155589205.png)

Also, here is my code for it:

`
            
BarcodeLib.Barcode b = new BarcodeLib.Barcode("6132502917419", BarcodeLib.TYPE.EAN13);

b.IncludeLabel = true;

System.Drawing.Image img = b.Encode(BarcodeLib.TYPE.EAN13, "6132502917419", Color.Black, Color.White, 1160, 480);
`

Can you please tell me what am i doing wrong? cuz i'm trying to get the first digit on the left of the first two lines.

Thank you very much!

**Comment by barnhill** [comment]
Im pretty sure I moved this below the starting lines.  You would need to modify the label method for EAN13 if you want to move it back on the left side of the lines.  Its going to require calculation of the width of the text since you have to start drawing the barcode on the right side of that.
