### ISSUE TITLE
EAN13 improvement

### ISSUE THREAD

**Issue by danigoffi** [barnhill/barcodelib#39]
Hello Brad,
First of all : I very appreciate your work!
I have made a little improvement to your barcode library, in order to show the EAN13 label in 'standard' format.
Since I'm newbie to GitHub, how can I submit you the code so you can check if it is a good improvement?
I tried to push the commit with VS2015 but I get back an error.
P.S. Forgive me for my bad english, it's not my main language..

Kind regards,
Daniele

**Comment by barnhill** [comment]
Just fork the project on GitHub and make your changes.  Then create a pull request in GitHub back to this library. I'll be glad to look at it.

**Comment by barnhill** [comment]
Addressed with bd7bf7940ff67f1aef36fb89eb226d58656f424f
