### ISSUE TITLE
GS1-128(EAN-128) Support

### ISSUE THREAD

**Issue by shamanson** [barnhill/barcodelib#42]
Hello,
Is it possible to add support for GS1-128(EAN-128) code?

**Comment by barnhill** [comment]
Code 128 is already supported.  GS1 is just a subset or set of rules on the data encoded.

**Comment by shamanson** [comment]
Thank you for answer, and for your library too :)




--------------------------------
Regards,
Tamaz Andriashvili.

**Comment by riplikash** [comment]
@barnhill It's good to know GS1 is supported, but I'm not seeing any documentation on how it would be configured to add the Function-1 character immediately after the start character.
