### ISSUE TITLE
Error when IncludeLabel is true and AlternateLable is null

### ISSUE THREAD

**Issue by liaoyalien** [barnhill/barcodelib#46]
Hi barnhill,

 I met below error when 'IncludeLabel' is true and AlternateLable is null.
![image](https://user-images.githubusercontent.com/12839801/40212747-3840de26-5a84-11e8-9d34-8a63fd475059.png)

From stack trace,  I guess that it could be a null exception because that the AlternateLable is null.
![image](https://user-images.githubusercontent.com/12839801/40212828-ba64dfba-5a84-11e8-80f4-4a431ef7bebb.png)

![image](https://user-images.githubusercontent.com/12839801/40212779-5e4d5afe-5a84-11e8-838c-becb47652e90.png)

**Comment by barnhill** [comment]
closing this issue as resolved with the above merge
