### ISSUE TITLE
The example does not generate code with label

### ISSUE THREAD

**Issue by honzakuzel1989** [barnhill/barcodelib#53]
Hello,
I tried your nice library and i was suprised that your example source code does not generate your example barcode (barcode with label). Why?? Is it any type of misunderstanding or incomplete example? 

Thanks!

**Comment by barnhill** [comment]
![capture](https://user-images.githubusercontent.com/3878158/48968350-fe557d00-efb3-11e8-8173-1bc803505b7c.JPG)

**Comment by barnhill** [comment]
I just used the example app and the default parameters EXCEPT I set generate label to true by checking the box.
