### ISSUE TITLE
The UPCA with IncludeLabel throws exception

### ISSUE THREAD

**Issue by honzakuzel1989** [barnhill/barcodelib#54]
Hello,
your example code generate barcode without label. When I set IncludeLabel property I get ArgumentNullException. I suppose that is because I have to set AlternateLabel but I do not understand why.

Is it a bug or a feature?

Thanks.

**Comment by barnhill** [comment]
@honzakuzel1989 I think this bug was just addressed in the latest pull https://github.com/barnhill/barcodelib/pull/57

**Comment by barnhill** [comment]
Closing unless you still see the bug
