### ISSUE TITLE
BarcodeLib Reference could not be found. 

### ISSUE THREAD

**Issue by kevball2** [barnhill/barcodelib#56]
When trying to build the .net core branch build and test app there is an error that the BarcodeLib reference in BarcordLibTest could not be found. Build fails to complete 

Steps to re-create

download net-core-conversion branch with GitHub desktop
launch solution files with VS 2017 (15.8.8) 
Build solution. 
Receive the following errors
![image](https://user-images.githubusercontent.com/22545150/47622998-affaae80-dad9-11e8-82f5-a0af01ec53f3.png)

Attempting to reference the dll from \bin\debug results in different errors due to referenced version mismatch

![image](https://user-images.githubusercontent.com/22545150/47623028-154e9f80-dada-11e8-9bf4-dfb3f02ffd84.png)

Tried resolving issues but no luck :(

**Comment by barnhill** [comment]
hum ... Ill take a look at this but its because I was converting this to a .NET core library so it can be more widely used and the test application doesnt allow inclusion of Core libs.  I might have to do some investigating to figure out how to handle this and have a build for .net core and standard in the project.

**Comment by barnhill** [comment]
I was thinking about this all wrong.  I should have been targeting .net standard and not .net core.  This would give this library the widest availability.

**Comment by barnhill** [comment]
@kevball2  want to take a look at the latest commit in that branch?  It should convert the library over to .NET Standard.  It does use a nuget package for System.Drawing.Common since thats not normally available in .NET Standard or Core.

**Comment by kevball2** [comment]
@barnhill  Everything loads better, Just have to work out the Nuget Package, The Nuget reference you have for the BarcodeStandard works fine, but the reference to it in the Example could not be found. 
![image](https://user-images.githubusercontent.com/22545150/47743948-333d1100-dc4e-11e8-8a29-4c2c2f0476ac.png)

This is most likely is due to my lack of knowledge with Nuget. Learning by doing!

**Comment by barnhill** [comment]
Granted I haven't uploaded to the nuget site as an official release till
that branch merges.

Brad Barnhill
bradbarnhill@hotmail.com
