### ISSUE TITLE
EGETXML-2: There was an error generating the XML document.

### ISSUE THREAD

**Issue by Sturzi79** [barnhill/barcodelib#59]
Updated to version 2.0 the library throws error described in title.
Downgraded to version 1.3 it works as expected with no error.

Sample code:
            var code = "85000923846235";

            BarcodeLib.Barcode b = new BarcodeLib.Barcode();
            b.Alignment = BarcodeLib.AlignmentPositions.CENTER;
            BarcodeLib.TYPE type = BarcodeLib.TYPE.Interleaved2of5;
            b.IncludeLabel = true;
            b.RotateFlipType = RotateFlipType.RotateNoneFlipNone;
            b.AlternateLabel = code + CalculateCheckDigit(code);
            b.LabelPosition = BarcodeLib.LabelPositions.BOTTOMCENTER;
            b.BarWidth = null;
            b.AspectRatio = null;

            b.Encode(type, code, Color.Black, Color.White, 300, 150);

Method "CalculateCheckDigit" generates as the name said a one digit checksum.

**Comment by barnhill** [comment]
I threw the following in the test app and it worked without error:

`            var code = "85000923846235";
            BarcodeLib.Barcode b = new BarcodeLib.Barcode();
            b.Alignment = BarcodeLib.AlignmentPositions.CENTER;
            BarcodeLib.TYPE type = BarcodeLib.TYPE.Interleaved2of5;
            b.IncludeLabel = true;
            b.RotateFlipType = RotateFlipType.RotateNoneFlipNone;
            b.AlternateLabel = code;
            b.LabelPosition = BarcodeLib.LabelPositions.BOTTOMCENTER;
            b.BarWidth = null;
            b.AspectRatio = null;

            barcode.BackgroundImage = b.Encode(type, code, Color.Black, Color.White, 300, 150);`

Can you post the contents of your CalculateCheckDigit(string) method?   I think you problem may be in there.

**Comment by Sturzi79** [comment]
public static int CalculateCheckDigit(string ean)
        {
            var multiplier = 3;
            var checkNumber = 0;
            var numb = 0;

            for (int i = 0; i < ean.Length; i++)
            {
                if (int.TryParse(ean.Substring(i, 1), out numb))
                {
                    checkNumber += numb * multiplier;
                    multiplier = (multiplier == 3) ? 1 : 3;
                }
            }

            var checkNumberPlus9 = checkNumber + 9;
            var nextMultipleOfTen = checkNumberPlus9 - (checkNumberPlus9 % 10); // nextMultipleOfTen ist jetzt das nächste Vielfache von zehn
            return nextMultipleOfTen - checkNumber;
        }

this is the CalculateCheckDigit method

**Comment by barnhill** [comment]
This check digit code is already in the library ... You are aware of that right?

**Comment by Sturzi79** [comment]
Do you mean the library has a built-in method to generate a check digit like the method above do it?
If so can you give me a hint where to find and to use? I can't find it by myself.

**Comment by barnhill** [comment]
Oops I mislead you.  There is no Mod10 check digit for Interleaved 2 of 5 but there will be soon :)
