### ISSUE TITLE
Code 128 barcodes text cuts off after 37 symbols

### ISSUE THREAD

**Issue by tsurrdurr** [barnhill/barcodelib#61]
Hello, I've encountered this bug (i think it is) where any symbols in StringToEncode past 37th passed to method
`barcode.Encode(TYPE.CODE128, "somelongtext", Color.Black, Color.White, 300, 150);`
aren't displayed as symbols under the bars. The bars for these cut off numbers though are still generated.
here for example:
`barcode.Encode(TYPE.CODE128, "236870469325449301543589144351218890486", Color.Black, Color.White, 300, 150);`
results in following:
![default](https://user-images.githubusercontent.com/17877463/51283286-c1789600-19f8-11e9-8983-adf6b7547073.png)
but without 2 last symbols it looks different:
![default](https://user-images.githubusercontent.com/17877463/51283351-f389f800-19f8-11e9-9339-3761f88d99fd.png)
I'd really want to keep these last 2 symbols still in the text under the bars. Can you please look into it?

**Comment by barnhill** [comment]
37 chars in 300px width?  Ill have to look but I think there is a way to specify the font to use.

**Comment by tsurrdurr** [comment]
Okay, my bad, the width advice actually worked. Increasing it to 315 let me fit in just those 2 extra symbols I wanted.
I thought it wouldn't work because I tested it in some older version of the library and it just stretched the symbols instead.
Thank you!

**Comment by barnhill** [comment]
Hahaha not a problem at all!!!  I just thought that was a bit small for that many chars.  Let me know if I can help you out in the future.
