### ISSUE TITLE
Visual Studio 2017 - .net framework 4.5.2

### ISSUE THREAD

**Issue by steveshourds** [barnhill/barcodelib#62]
Severity	Code	Description	Project	File	Line	Suppression State
Error		Could not install package 'BarcodeLib 2.2.1'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.5.2', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

**Comment by PhilipMur** [comment]
I am also experiencing the same problem . 
I have tried to install on every target frame work from ( 4.5.0 > 4.7.1 ) .
It will not install BarcodeLib versions ( 2.0.0 > 2.2.1) from the NuGet .
It will install version 1.3.0.
Can you make revisions to the target dependencies the same as version 1.3.0 please.
Very good project by the way.

**Comment by barnhill** [comment]
Im going to setup a new project here and use 2.2.1 from nuget and see what happens.

**Comment by barnhill** [comment]
From what Im seeing the System.Drawing.Common which is a dependency of v2.0.0+ requires .NET 4.6.1 or greater to be the target.  With v2 of the library there was a HUGE refactor to be a .NET standard library instead of just targeting windows deployments, it was changed to support linux and mono developers too.  Let me know if this makes sense.  v1.3.0 thats still available for installation will support older frameworks pre-4.6.1

**Comment by PhilipMur** [comment]
Hello,

I have targeted from 4.5. NET all the way up to 4.7. NET and rebuilt
everytime before trying to get again to install BarcodeLib version 2+ from
NuGet.

I am using Visual Studio 2015 express and it would not install.
I will try again in Visual Studio 2017 community later and see if it will
install.

**Comment by PhilipMur** [comment]
I have tried with 30 mins to try install BarcodeLib v2.2.1 on Visual Studio Express 2015 target framework 4.7 and installed System.Drawing.Common v4.5.1 but without success (FAILED) .

I am however able to install BarcodeLib v2.2.1 on Visual Studio 2017 target framework 4.7 and Installed System.Drawing.Common v4.5.1 and success ( ALL OK ).

I don't know why that is and i cannot spend too much time on it but the attached screenshot should help people trying to install this library  ( just download both shown from NuGet and install ).

Thanks for taking your time to develop this library by the way really helped me and is easy to use.

Philip

![screenshot 1051](https://user-images.githubusercontent.com/27295232/51808698-2badf800-228f-11e9-8961-6c19d942443f.png)

**Comment by barnhill** [comment]
Awesome!!! Glad you find it easy to use.

**Comment by barnhill** [comment]
@PhilipMur are we good to close this?  Is there something else I need to address?

**Comment by PhilipMur** [comment]
Yep you resolved the issue thanks,
close it.

Philip

**Comment by AnthonyVO** [comment]
@barnhill, I realize this issue is closed but I found another solution I would like to discuss with you before releasing. Not sure how I can send you a private gist or message.

**Comment by barnhill** [comment]
Open a new issue and we can discuss in there.  I like to keep issues from
different parties separate.
