### ISSUE TITLE
text to be clearer?

### ISSUE THREAD

**Issue by cramirezoliveros** [barnhill/barcodelib#63]
is there a way for the label(text) to be clearer?, label(text) comes out pixilated
Thank you

**Comment by barnhill** [comment]
@cramirezoliveros do you have an example that you are generating that is pixelated?

**Comment by cramirezoliveros** [comment]
![captura](https://user-images.githubusercontent.com/2816203/52749285-adec2b00-2fb6-11e9-8140-f333b55fcf81.PNG)

**Comment by barnhill** [comment]
What encoding are you using?  This does not look possible since the rest of the image isnt pixelated but only the text is.   Something is fishy here.

**Comment by cramirezoliveros** [comment]
I'm using Code 128

**Comment by barnhill** [comment]
Size you are generating?  I am getting clear C128 encodings with labels.

**Comment by barnhill** [comment]
@cramirezoliveros  Im going to close this as I am unable to recreate this without more information. (Size specified when encoding, Code 128 encoding type selected to encode with ... etc)

**Comment by rob313663** [comment]
Doing a default size Code 128 gives a bit pixelated text for me:

var b = new BarcodeLib.Barcode();
b.IncludeLabel = true;
var i = b.Encode(BarcodeLib.TYPE.CODE128, "AGG460");
i.Save(@"C:\temp\c128fuzzy.png", ImageFormat.Png);

Doing:
var i = b.Encode(BarcodeLib.TYPE.CODE128, "AGG460", 1000, 300);

Gives a much bigger barcode but very small and pixelated text.

I do not get that smoothed pixelated text though, maybe he output it to a lossy image format.

I agree though, @cramirezoliveros needs to attach sample code for the report.

**Comment by barnhill** [comment]
Yeah Im not sure but it does look like a lossy file format from the pixelated image.

**Comment by barnhill** [comment]
Closing since he has not replied in 10 months
