### ISSUE TITLE
code-128 

### ISSUE THREAD

**Issue by vidoa** [barnhill/barcodelib#64]
Hi,
I'm trying to generate a code-128 barcode using the library. The problem is that the barcode generated differs from the barcode generated from any other online tool I tried. Most of it is the same but there is one section that is different. I was able to read both barcodes using a free android barcode reader app and the data is the same. I'm a bit confused how two different code-128 barcodes can represent the same data. I tried different versions of code-128 but the generic code-128 is the closest to the online tools results.
A screen shot of the results is attached. The difference is marked in red. For the screen shot I used the test desktop application but I have the same results when using the library.
Regards.
![Code128Test](https://user-images.githubusercontent.com/19596897/54692624-aa8b1880-4afb-11e9-8ab8-03583f4b936a.jpg)

**Comment by barnhill** [comment]
The specs for dynamic code 128 are vague. It will automatically switch
between encodings based on the data being encoded to try to use code128-C
if it can.  This will save space and generate a more compressed barcode if
possible.  When it switchs encodings can be left up to the implementation
though to some degree.  Some are more aggressive than others.

Brad Barnhill, MSN, RN
bradbarnhill@hotmail.com

**Comment by vidoa** [comment]
That explains the difference.
Is there a way to force the library to encode using code128 and not switching to 128-C regardless the data?
Thank you.

**Comment by barnhill** [comment]
Yea you can force it to A, B or C.  Now your data will have to be
compatible with that encoding type and if it's all numeric I'd suggest C to
compress the barcode by half.

Brad Barnhill, MSN, RN
bradbarnhill@hotmail.com

**Comment by vidoa** [comment]
After some digging I found out why the barcodes are different.
Because my numbers have odd (19) digits if I use dynamic code 128 and don't specify the sub-type (A, B or C) your library is using code128C for the first 18 digits (9 groups x 2 digits) and code128A for the last 19th single digit. All others code128 generators are using code128B for the last 19th single digit. Technically, both barcodes are valid and scanners can read them. I guess there isn't a way to force the library to use 128B for the last odd digit without changing the source code.

**Comment by vidoa** [comment]
I switched the two IFs that are choosing the encoding (128A or128B) for the last single digit in Code128.cs at lines 194 and 209 and now it works as I want. Now 128B has higher priority than 128A. For me 128B looks more common in cases like this.
