### ISSUE TITLE
value cannot be null error while converting number to TYPE UPC-A

### ISSUE THREAD

**Issue by BhargavaNRao** [barnhill/barcodelib#65]
Hi,

I am using BarcodeLib version 1.3.0 as my project framework is below 4.6.1.

I am not able to convert a number to the barcode of TYPE UPC-A. Though I can convert to another type like CODE-128.

Below is the error screenshot which I am getting.
![image](https://user-images.githubusercontent.com/37331431/55216315-68ac5180-5222-11e9-9575-36c43807bb4d.png)

**Note:** All parameters have values and nothing is null.

Also please find the stack trace which I got from exception block - 
at System.String.StartsWith(String value)
   at BarcodeLib.Barcode.Generate_Image()
   at BarcodeLib.Barcode.Encode()
   at BarcodeLib.Barcode.Encode(TYPE iType, String StringToEncode, Color ForeColor, Color BackColor, Int32 Width, Int32 Height)
   at TagUpTool.Controllers.TagUpToolController.GetBarcode(String UPCNbr)

Awating your response.

**Comment by barnhill** [comment]
@BhargavaNRao Ill take a look.

**Comment by barnhill** [comment]
@BhargavaNRao it appears this is probably something that was fixed in 2.2.1 with this commit 39f691a29071f2cfed0cc15f0107b9dc31cd0e66

**Comment by barnhill** [comment]
@BhargavaNRao can you confirm?

**Comment by BhargavaNRao** [comment]
@barnhill From the commit  #39f691a, I got to know that the exception occurs when we include the label. So I am generating barcode without the label. This resolves the issue.

**Comment by barnhill** [comment]
Closing as resolved with https://github.com/barnhill/barcodelib/commit/39f691a29071f2cfed0cc15f0107b9dc31cd0e66
