### ISSUE TITLE
String parameter, can JSON be used somehow?

### ISSUE THREAD

**Issue by nstone101** [barnhill/barcodelib#68]
Would there be a way to use JSON as the encode-able string? Has anyone else tried that. 
I've had some issues with compiling the information that I want encoded with under my barcode. What's the best way to do this? I just said json as it's a natural go-to for alot of things, and it seems to be popular in the php bunch of barcode apps and plugins. I'm building a client to take in a create barcodes. I'm reading them in Json format (although that may change). Basically just keeping a CRUD client and database of active vs inactive equipment in my company, and tracking by location and device types, printers, towers, etc. Basic IT stuff.  My issue is using json, but it's mostly theoretical questioning than an issue with your code. Love it so far, just want to make it work for me if possible.

**Comment by barnhill** [comment]
I guess you could but I'm sure even code 128 is going to be too long.  This
sounds like a 2d barcode scenario.

Brad Barnhill, MSN, RN
bradbarnhill@hotmail.com

**Comment by barnhill** [comment]
Closing as answered
