### ISSUE TITLE
Single .cs file delivery for c# library projects.

### ISSUE THREAD

**Issue by AnthonyVO** [barnhill/barcodelib#73]
I also ran into the issue: https://github.com/barnhill/barcodelib/issues/62

I found that the problem was not with the code but the project container.

By extracting and recomposing the code from this project into a single class file, I found that I could solve this issue and gain a couple of other valuable wins.  No extra DLL to maintain and distribute, and smaller builds.

By a single class file I don't mean a single c# class, but rather a single .cs file structured with all the important pieces of your project, including the license.  No code is changed, the project contents are simply shifted into a single file.   I have created a secret gist here: https://gist.github.com/AnthonyVO/8c301818fc9ef86b809ef1ebe0630786

Creating this by hand would have been tiresome.  It would also make it very difficult to see the differences between releases.  To combat this I have created a relatively simple C# program to automate the process.  Your project was the project that triggered the creation.  I intend to push my utility to github shortly, I just need to I take some time to clean it up.  My thought is that a tool like this could become part of a projects build process, creating a single file version of the project for those who desire it.

The Asks:

1) I am not asking you to restructure your code.   The beauty of this is that you get to maintain this project as is.

2) I don't want to become the maintainer of single file versions of other peoples projects.  This project is yours and the focus and credit should remain here.  Therefore I am asking you to consider maintaining a single file version of this project.  (Built automatically of course)

3) I am not asking for endorsement, at least not explicitly.  I have already received some heat for this idea... See: https://stackoverflow.com/questions/57727349/combine-a-c-sharp-project-into-a-single-class-file

4) What I am asking for is permission to use your project and the gist as an example when I do the readme for my GitHub project.

Anthony

**Comment by barnhill** [comment]
I dont care that you use it as its open source and free.  I do not recommend doing this from a maintenance standpoint.  It pretty much goes against modular and sensible design but I guess everyone has a need.

**Comment by AnthonyVO** [comment]
> If you copy this code into a single .cs file how do you get updates when I change something or fix a bug? 

That is the reason for the program.   If I did this by hand then you are correct, it would be insane.

Because the code always builds an identical structure, then I can easily diff between them to see the changes.  I just watch for a new release, grab a copy and convert it to a single file.   I can then easily diff the versions.  In some ways it is even easier because all of your project's changes are in one file.   I could even follow code moves between files.

The BIGGEST thing this buys me is that I don't need to convert my project to a different framework version.  This frees both you and I to make our own project container choices.   I have a specific need that ties me to 4.5.2.

The second item this buys me is that my project structure and build process is now simpler and fail safe.

You may disagree but I have had plenty of experience with distributed code and the very painful results when things don't go as planned.   This includes unexpected / uncaught updates that totally trashed builds, updates that schlepped in a whole new raft of dependencies, hosted dependencies that simply disappeared (infamous case, can't find reference right now), etc...   All of which have cost me lots of unexpected time, usually when I least had time time available.

I am a firm believer in the KISS principle.  My translation = (Keep it Stupidly Simple).

**Comment by barnhill** [comment]
Im also a believer in the KISS method ... this just causes you more work to stay up to date with dependencies.  This type of dependency management just does not scale, takes lots of work to update each dependency ... for no real benefit.

You can keep your dependencies at a certain version and it wont get auto updated till you tell it to use a newer version of that dependency.

Ill close with this question. In a project that has 20+ dependencies (and a common run of the mill Android application will) ... would you do this for every one of those?
