### ISSUE TITLE
QR Code

### ISSUE THREAD

**Issue by jaymarvels** [barnhill/barcodelib#74]
Is there anyway to generate QR Codes with this library?

**Comment by SjsolisZXA** [comment]
QR Code support would reduce the number of NuGet packages I use.

**Comment by KasatO** [comment]
> Is there anyway to generate QR Codes with this library?

You are Developer next FMM Pre Game Editor?

**Comment by jaymarvels** [comment]
@KasatO  Yep :)

**Comment by KasatO** [comment]
Can you open source FMM17 Pre Game Editor for me?

**Comment by KasatO** [comment]
@jaymarvels  Can you open source FMM17 Pre Game Editor for me?

**Comment by barnhill** [comment]
Id love to have QR code support in the library if anyone knows enough about QR codes to help

**Comment by barnhill** [comment]
I accept pull requests if you want to add it
