### ISSUE TITLE
Missing Numbers on Barcodes

### ISSUE THREAD

**Issue by SjsolisZXA** [barnhill/barcodelib#75]
Hello,

For Types UPCA, and CODE128C bar codes, the numbers are not generated with the output Image object. Below is my code:

```
            Barcode b = new Barcode();
            Image img = b.Encode(TYPE.CODE128C, code, Color.Black, Color.White, 500, 130);
```

**Comment by AnthonyVO** [comment]
You should add the following..
`b.IncludeLabel = true;`
