### ISSUE TITLE
Need AllowPartiallyTrustedCallers for SSRS generation (again!)

### ISSUE THREAD

**Issue by AndrewZenith** [barnhill/barcodelib#78]
This was previously in the assemblyinfo.cs:

[assembly:AllowPartiallyTrustedCallers]

From what I see on .Net Standard 2.0 this can just be added before the namespace.

**Comment by barnhill** [comment]
Added this to the main BarcodeLib.cs file before the namespace

**Comment by barnhill** [comment]
published a new version of the nuget package (2.2.3.0) that should have this in there.  Log a new issue if its not fixed.  Closing this one as fixed with: https://github.com/barnhill/barcodelib/commit/a51edbc3cef27d4cd896538e3cc1eb019d3bdec8
