### ISSUE TITLE
[Question] System.Drawing.Common 4.0.0.1

### ISSUE THREAD

**Issue by rob313663** [barnhill/barcodelib#80]
![image](https://user-images.githubusercontent.com/23123057/68159147-80368000-ff51-11e9-9146-e08553eb4722.png)

I have managed to solve this, a bit brutally, probably in the wrong way.

I am planning to make changes that will affect csproj and maybe the solution and then my brutal solution to this problem won't work.

I am thinking this has to depend on something in my environment that is wrong. Could it be me not having .Net core 2.0 installed?

Edit:

Installed .Net Core 3.

I tried (in PM console in VS 2019):
PM> Install-Package System.Drawing.Common -Version 4.0.0

It worked, installed stuff but then I get:
![image](https://user-images.githubusercontent.com/23123057/68238973-72910100-000a-11ea-8635-16007ecb2954.png)

I checked what Install-Package did to the .csproj file, and found diff on this line:
<HintPath>..\packages\System.Drawing.Common.4.5.1\lib\net461\System.Drawing.Common.dll</HintPath>

Then I did:
PM> Install-Package System.Drawing.Common -Version 4.5.1

Didn't work either.

Then I reverted everything back. Just did "Install-Package System.Drawing.Common -Version 4.5.1" but I still get the same problem in BarcodeStandardExample.

What am I doing wrong?

**Comment by barnhill** [comment]
Im not sure but I do have .NET Core 2.0 installed
