### ISSUE TITLE
I can't install barcodelib, could someone help me?

### ISSUE THREAD

**Issue by Guyz1** [barnhill/barcodelib#84]
I'm getting this error message from installing via nuget:

```
Severity	Code	Description	Project	File	Line	Suppression State
Error		Could not install package 'BarcodeLib 2.2.5'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.5.2', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.		
```		

Could someone help me install?

**Comment by barnhill** [comment]
What version of the framework does your application target

**Comment by Guyz1** [comment]
> What version of the framework does your application target

I can't remember because i changed it

after changing to .net framework 4.7.2 it just installs and works fine!

**Comment by Guyz1** [comment]
How do you usually install it?

Do you just install it from nuget?

I assumed nuget was hassle free but I'm wrong sometimes things don't install and I don't know why

**Comment by danielchalmers** [comment]
barcodelib targets **.NET Standard 2.0** so you'll need to target at least **.NET Framework 4.6.1** to use it.
https://docs.microsoft.com/en-us/dotnet/standard/net-standard

you should also be using Visual Studio 2019 as .NET Standard didn't even exist in 2015.

**Comment by Guyz1** [comment]
well i managed to install it by downloading the package from nuget and then manually adding the barcodestandard.dll to the references 

rebuild the solution..
and I'm glad it works! 

I don't know what strange weird things are preventing me from installing via nuget so doing like i did manually seems to always work
