### ISSUE TITLE
Exception: EGENERATE_IMAGE-2: Image size... less than 1 pixel

### ISSUE THREAD

**Issue by kinguru** [barnhill/barcodelib#85]
Hi!
I'm calling a lib like shown below on the screenshot and getting exception about 1px.
How should I generate a barcode?

![image](https://user-images.githubusercontent.com/54497/78817371-ba61ed00-79db-11ea-8d23-c014875e929d.png)

Thank you

**Comment by binki** [comment]
Hi @kinguru 

This means that the default width of the image which `BarcodeLib` would try to generate is too skinny such that some bars which must be present could be invisible, preventing it from scanning. You can make it wider. The default value is 300, but maybe 500 would work. Maybe doing something like the following would work for a GUID?

```csharp
var b = new BarcodeLib.Barcode();
using (var img = b.Encode(BarcodeLib.TYPE.CODE128, jobGUID.ToString(), 500, 150)) {
}
```

If you still get the same error, increase the number 500 more drastically. Perhaps 750. You will get a large image, but it should at least work at some point ;-).

**Comment by kinguru** [comment]
The case is that I need minimum width barcode :) I know it is 420-450 px but could vary... As I understand there is no reason for you to limit it to some default value (300?) as you should already know the length of barcode generated.

**Comment by binki** [comment]
@kinguru I see. It looks like you should be able to do this with the [`Barcode.BarWidth`](https://github.com/barnhill/barcodelib/blob/bbd961bcb1293af1144d2f2a1f18d9f108e7ddfd/BarcodeStandard/BarcodeLib.cs#L179) property. Here is an example of using that property:

```csharp
var barcode = new BarcodeLib.Barcode()
{
    // Use the minimum bar width of 1 pixel. Setting this causes
    // BarcodeLib to ignore the Width property and create the minimum-width
    // barcode.
    BarWidth = 1,
};
using var image = barcode.Encode(BarcodeLib.TYPE.CODE128, Guid.NewGuid().ToString());
using var outputStream = System.IO.File.OpenWrite("image.png");
image.Save(outputStream, System.Drawing.Imaging.ImageFormat.Png);
```
Some image widths I got were 607px, 541px, and 563px—seems like it is a variable width encoding ;-).

**Comment by barnhill** [comment]
this error is valid in that it lets you know you are trying to generate an image smaller than it can draw it.  It cant draw  bars less than 1 pixel so if it determines the width of the barcode wont hold the whole image when drawing 1px width bars ... it throws this.  (As @binki alluded to)

**Comment by barnhill** [comment]
@binki Im gonna close this out unless you think we should leave this open?

**Comment by binki** [comment]
@barnhill It looks ready to be closed to me, please go ahead!

**Comment by barnhill** [comment]
Closing this as answered
