### ISSUE TITLE
Barcode without white border

### ISSUE THREAD

**Issue by kzimny** [barnhill/barcodelib#88]
How to generate barcode without white border on left and right side?
![image](https://user-images.githubusercontent.com/12007674/82994260-25a26580-a002-11ea-93de-2e0f45849e35.png)

**Comment by binki** [comment]
Hi @kzimny,

The default setting is to use a [`Width` of 300 pixels](https://github.com/barnhill/barcodelib/blob/bbd961bcb1293af1144d2f2a1f18d9f108e7ddfd/BarcodeStandard/BarcodeLib.cs#L47). Different values can result in different widths of the the bars. If you want the barcode’s width to be calculated based on how wide the barcode has to be to display the data, you can set the [`BarWidth`](https://github.com/barnhill/barcodelib/blob/bbd961bcb1293af1144d2f2a1f18d9f108e7ddfd/BarcodeStandard/BarcodeLib.cs#L179) property. For example, you can set it to `1` to have the smallest bar width be 1 pixel. The result will be no white on the sides of the barcode.

Here is some example usage which saves the minimum width barcode to a PNG file:

```csharp
var barcode = new BarcodeLib.Barcode()
{
    // Use the minimum bar width of 1 pixel. Setting this causes
    // BarcodeLib to ignore the Width property and create the minimum-width
    // barcode.
    BarWidth = 1,
};
using var image = barcode.Encode(BarcodeLib.TYPE.CODE128, "data");
using var outputStream = System.IO.File.OpenWrite("image.png");
image.Save(outputStream, System.Drawing.Imaging.ImageFormat.Png);
```

**Comment by kzimny** [comment]
Yes, it works perfectly! Thank you very much. Great library.
