### ISSUE TITLE
why am getting Trial-Barcode on Barcode Images

### ISSUE THREAD

**Issue by MrArif-5** [barnhill/barcodelib#90]
![20200521232649](https://user-images.githubusercontent.com/57086628/84229036-396fc080-ab06-11ea-8def-546ad129e6e1.Jpeg)

**Comment by binki** [comment]
@MrArif-5 I think you are probably putting that there yourself? What NuGet package are you using? Can you show the code that you used to generate that barcode image? Are you sure this GitHub repository is related to what you’re doing?

**Comment by barnhill** [comment]
@MrArif-5 this is not coming from the library.  Nothing in here generates that.

**Comment by barnhill** [comment]
You can probably contact these people since it appears you are using their library and not this one.  http://www.onbarcode.com/support/
