### ISSUE TITLE
NullReferenceException when using US EAN13s.

### ISSUE THREAD

**Issue by Matamanthemaster** [barnhill/barcodelib#92]
Hello.

I installed your lib through NuGet, v2.2.5 and am unable to generate any EAN13 beginning with 0, which is a US range. beginning with 02 also caused the issue, however 20 was encoded (though the label was a slightly unexpected value). It throws a NullReferenceException when trying to encode an image, and if I try to use GenerateBarcode(), it appears as most fields are null.
![image](https://user-images.githubusercontent.com/13311140/86587114-f5df6980-bf80-11ea-81b4-2698ae660db5.png)
The test data I am using is from a real named product I bought in a shop. Am I using the library correctly or is there a bug? I have tried multiple methods to try and get my current code scheme to work, and changing the first number system digit has been the only method that has worked.

Edit: Forgot to mention, the stack trace at runtime is:
`   at BarcodeLib.Symbologies.EAN13.Encode_EAN13()`

I am willing to accept if this is a layer 8 issue. All I can gleam from my lack of experience with nonstandard libs, it appears to me an issue with the lib.

Thank you for your time,
Matthew Smith

**Comment by antoineloos** [comment]
I have the same bug here, any update or workaround ?

**Comment by Pushan12** [comment]
![image](https://user-images.githubusercontent.com/21195975/88324369-3d1b7780-cd41-11ea-8589-164a2602e0be.png)
Need to tweak something like this to get. I tried and got
this
![image](https://user-images.githubusercontent.com/21195975/88324525-6f2cd980-cd41-11ea-8f47-6e6003c10acc.png)

**Comment by barnhill** [comment]
![image](https://user-images.githubusercontent.com/3878158/90716938-cc01ae00-e273-11ea-9c43-38c648c891ae.png)

**Comment by barnhill** [comment]
Im unable to reproduce.  Any other suggestions on recreation?

**Comment by Pushan12** [comment]
Let me try and tweak in your application. I have tweaked it my application.

**Comment by Matamanthemaster** [comment]
I statically analysed your example and using your data from your last post. I still got this exception thrown. If in visual studio I say to not break on the exception thrown by BarcodeStandard.dll, then it will generate the barcode. This only occurred however when using US EAN13s ans stated prior, as no exception is thrown using other EANs I tried. I guess I didn't know how to use visual studio for debugging? It just seems odd to me to ignore exceptions thrown from a lib and have everything work normally.

![image](https://user-images.githubusercontent.com/13311140/91184135-2f606580-e6e4-11ea-8022-5756e0cb6b50.png)

Thank you for your time,
Matthew Smith

**Comment by barnhill** [comment]
If you are generating a lot of barcodes with that code above you are going to be creating a lot of objects in that getter which might cause a lot of GC.
