### ISSUE TITLE
Wrapper on barcodelib

### ISSUE THREAD

**Issue by sinhngoc2008** [barnhill/barcodelib#95]
Hello
I wanna write a wrapper on your lib for my purpose but I got not thing when I use function GenerateBarcode();
I read your code and I think there may have some points that is not correct yet.
- In GenerateBarcode() function. It should be "return ibarcode.Encoded_Value;" instead of "return this.Encoded_Value;". Because Encoded_Value contain nothing.
- From the Endcode() function. It should be "this.Encoded_Value  = GenerateBarcode();"
instead of 
GenerateBarcode();
this.Encoded_Value = ibarcode.Encoded_Value;

**Comment by barnhill** [comment]
Actually its  `GenerateBarcode();` that should return nothing.  So Ive changed that method to be a `void` return type.  It generates the object ibarcode and then that is used throughout the reset of the encode method.

**Comment by barnhill** [comment]
I changed it to:
`this.Encoded_Value = GenerateBarcode();`
even though this is probably a left over from the early days and just never got consolidated the functionality is still the same.  But `GenerateBarcode()` now will return a value in the next release.

**Comment by barnhill** [comment]
Published 2.2.6 which fixes this just now.  Closing issue.
