### ISSUE TITLE
Security warning for XML deserialization

### ISSUE THREAD

**Issue by mpondo** [barnhill/barcodelib#96]
While doing a security review of the library before including it in a project, the code for deserializing from xml was raised as a potential security concern.  This occurs in both GetImageFromXML and GetSaveDataFromFile.  

Here is a link to information about the Security warning:
https://docs.microsoft.com/en-us/visualstudio/code-quality/ca5369?view=vs-2019

**Comment by barnhill** [comment]
Ill take a look at this.

**Comment by barnhill** [comment]
Addressed in https://github.com/barnhill/barcodelib/pull/117
