### ISSUE TITLE
Interleaved2of5_Mod 10 checksum calculation is not correct

### ISSUE THREAD

**Issue by makuep** [barnhill/barcodelib#97]
There are two problems in the algorithm: 
1. it sums up the ASCII value of the chars not the integer value. Either char.getNumericValue or some char magic like  RawData[i]-'0' should be used.
2. the result should be the number that when added to the sum is a multiple of 10. So "10 - (sum%10)".

**Comment by barnhill** [comment]
I suspect that you were referring to the `CalculateMod10CheckDigit` method?

**Comment by barnhill** [comment]
Have a look at https://github.com/barnhill/barcodelib/pull/103 as the proposed fix for this. @makuep and @binki

**Comment by barnhill** [comment]
Closing this with #103
